name: Setup

inputs:
  xcode:
    description: 'Setup Xcode'
    type: boolean
    required: false
    default: false

runs:
  name: Setup
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'
    - name: Install Turbo CLI
      shell: bash
      run: pnpm add --global turbo
    - name: Install NPM Dependencies
      shell: bash
      run: pnpm install
    - name: Setup Xcode
      if: inputs.xcode
      shell: bash
      run: sudo xcode-select --switch $(ls /Applications/Xcode*.app | sort --version-sort | tail -n 1)
