packages:
  - apps/*
  - packages/*
  - tooling/*
  - supabase
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - canvas
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - supabase
  - unrs-resolver
