packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.30.0
  prettier: ^3.6.2
  tailwindcss: ^4.1.10
  typescript: ^5.8.3
  zod: ^3.25.74
  '@tanstack/react-query': 5.80.7
  '@tanstack/react-query-devtools': ^5.80.7
  '@tanstack/react-query-next-experimental': ^5.80.7
  '@trpc/client': ^11.4.1
  '@trpc/tanstack-react-query': ^11.4.1
  '@trpc/server': ^11.4.1

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': ~19.0.10
    '@types/react-dom': ~19.0.6

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - canvas
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - supabase
  - unrs-resolver

patchedDependencies:
  '@pdfme/generator': patches/@pdfme__generator.patch
