import { MD3Theme } from 'react-native-paper';
import { Platform } from 'react-native';

export const buildSurveyTheme = (theme: MD3Theme) => ({
  cssVariables: {
    '--sjs-font-family': Platform.OS === 'ios' ? 'sans-serif' : theme.fonts.bodyMedium.fontFamily,
    '--sjs-font-size': `${theme.fonts.bodyLarge.fontSize}px`,
    '--sjs-corner-radius': `${theme.roundness * 2}px`,
    '--sjs-base-unit': '8px',
    '--sjs-shadow-small': '0px 1px 2px 0px rgba(0, 0, 0, 0.35)',
    '--sjs-shadow-inner': 'inset 0px 1px 2px 0px rgba(0, 0, 0, 0.2)',
    '--sjs-border-default': theme.colors.outline,
    '--sjs-general-backcolor': theme.colors.surface,
    '--sjs-general-forecolor': theme.colors.onSurface,
    '--sjs-general-dim-forecolor': theme.colors.onSurface,
    '--sjs-secondary-backcolor': theme.colors.secondary,
    '--sjs-secondary-forecolor': theme.colors.onSecondary,
    '--sjs-shadow-small-reset': `0px 0px 0px 0px ${theme.colors.shadow}`,
    '--sjs-shadow-medium': `0px 2px 6px 0px ${theme.colors.shadow}`,
    '--sjs-shadow-large': `0px 8px 16px 0px ${theme.colors.shadow}`,
    '--sjs-shadow-inner-reset': `inset 0px 0px 0px 0px ${theme.colors.shadow}`,
    '--sjs-border-inside': theme.colors.outlineVariant,
    '--sjs-special-red-forecolor': theme.colors.onError,
    '--sjs-special-green': theme.colors.tertiary,
    '--sjs-special-green-forecolor': theme.colors.onTertiary,
    '--sjs-special-blue': theme.colors.primary,
    '--sjs-special-blue-forecolor': theme.colors.onPrimary,
    '--sjs-special-yellow': theme.colors.secondary,
    '--sjs-special-yellow-forecolor': theme.colors.onSecondary,
    '--sjs-article-font-xx-large-textDecoration': 'none',
    '--sjs-article-font-xx-large-fontWeight': '700',
    '--sjs-article-font-xx-large-fontStyle': 'normal',
    '--sjs-article-font-xx-large-fontStretch': 'normal',
    '--sjs-article-font-xx-large-letterSpacing': '0',
    '--sjs-article-font-xx-large-lineHeight': '64px',
    '--sjs-article-font-xx-large-paragraphIndent': '0px',
    '--sjs-article-font-xx-large-textCase': 'none',
    '--sjs-article-font-x-large-textDecoration': 'none',
    '--sjs-article-font-x-large-fontWeight': '700',
    '--sjs-article-font-x-large-fontStyle': 'normal',
    '--sjs-article-font-x-large-fontStretch': 'normal',
    '--sjs-article-font-x-large-letterSpacing': '0',
    '--sjs-article-font-x-large-lineHeight': '56px',
    '--sjs-article-font-x-large-paragraphIndent': '0px',
    '--sjs-article-font-x-large-textCase': 'none',
    '--sjs-article-font-large-textDecoration': 'none',
    '--sjs-article-font-large-fontWeight': '700',
    '--sjs-article-font-large-fontStyle': 'normal',
    '--sjs-article-font-large-fontStretch': 'normal',
    '--sjs-article-font-large-letterSpacing': '0',
    '--sjs-article-font-large-lineHeight': '40px',
    '--sjs-article-font-large-paragraphIndent': '0px',
    '--sjs-article-font-large-textCase': 'none',
    '--sjs-article-font-medium-textDecoration': 'none',
    '--sjs-article-font-medium-fontWeight': '700',
    '--sjs-article-font-medium-fontStyle': 'normal',
    '--sjs-article-font-medium-fontStretch': 'normal',
    '--sjs-article-font-medium-letterSpacing': '0',
    '--sjs-article-font-medium-lineHeight': '32px',
    '--sjs-article-font-medium-paragraphIndent': '0px',
    '--sjs-article-font-medium-textCase': 'none',
    '--sjs-article-font-default-textDecoration': 'none',
    '--sjs-article-font-default-fontWeight': '400',
    '--sjs-article-font-default-fontStyle': 'normal',
    '--sjs-article-font-default-fontStretch': 'normal',
    '--sjs-article-font-default-letterSpacing': '0',
    '--sjs-article-font-default-lineHeight': '28px',
    '--sjs-article-font-default-paragraphIndent': '0px',
    '--sjs-article-font-default-textCase': 'none',
    '--sjs-general-backcolor-dim': theme.colors.background,
    '--sjs-primary-backcolor': theme.colors.primary,
    '--sjs-primary-forecolor': theme.colors.onPrimary,
    '--sjs-special-red': theme.colors.error,
  },
});