import {
  barcodes,
  checkbox,
  date,
  dateTime,
  ellipse,
  image,
  line,
  multiVariableText,
  radioGroup,
  rectangle,
  select,
  svg,
  table,
  text,
  time,
} from '@pdfme/schemas';
import { signature } from './signature';

export const plugins = {
  Checkbox: checkbox,
  // EAN8: barcodes.ean8,
  // Code39: barcodes.code39,
  Code128: barcodes.code128,
  Date: date,
  DateTime: dateTime,
  // JAPANPOST: barcodes.japanpost,
  EAN13: barcodes.ean13,
  Ellipse: ellipse,
  Image: image,
  Line: line,
  'Multi-Variable Text': multiVariableText,
  QR: barcodes.qrcode,
  RadioGroup: radioGroup,
  Rectangle: rectangle,
  Select: select,
  Signature: signature,
  SVG: svg,
  Table: table,
  Text: text,
  Time: time,
  // NW7: barcodes.nw7,
  // ITF14: barcodes.itf14,
  // UPCA: barcodes.upca,
  // UPCE: barcodes.upce,
  // GS1DataMatrix: barcodes.gs1datamatrix,
  // PDF417: barcodes.pdf417,
};
