name: Check

on:
  push:
  workflow_call:
    inputs:
      working-directory:
        description: Working directory to run checks in
        required: true
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm exec turbo run lint:check
        working-directory: ${{ inputs.working-directory }}

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm exec turbo run format:check -- .
        working-directory: ${{ inputs.working-directory }}

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm exec turbo run build:check
        working-directory: ${{ inputs.working-directory }}
