name: Mobile Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to build for
        required: true
        type: choice
        options:
          - production
          - preview
  workflow_call:
    inputs:
      environment:
        description: Environment to build for
        required: true
        type: string

defaults:
  run:
    working-directory: 'apps/mobile'

concurrency:
  cancel-in-progress: true
  group: ${{ inputs.environment }}-mobile-build

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: ios
            os: macos-latest
          - platform: android
            os: ubuntu-latest

    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    environment: ${{ inputs.environment }}
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm add --global eas-cli
      - id: build
        run: |
          pnpm build:${{ matrix.platform }} --profile ${{ inputs.environment }}
          echo "artifact-path=$(realpath build/*)" >> $GITHUB_OUTPUT
      - run: ls build/*
      - id: diawi
        uses: rnkdsh/action-upload-diawi@v1.5.9
        with:
          token: ${{ secrets.DIAWI_TOKEN }}
          file: ${{ steps.build.outputs.artifact-path }}
      - run: |
          PLATFORM="${{ matrix.platform }}"
          echo "## ${PLATFORM^} App" >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.diawi.outputs.url }} >> $GITHUB_STEP_SUMMARY
          echo ![QR Code](${{ steps.diawi.outputs.qrcode }}) >> $GITHUB_STEP_SUMMARY

  update:
    name: Update
    runs-on: macos-latest
    environment: ${{ inputs.environment }}
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm add --global eas-cli
      - run: eas env:pull ${{ inputs.environment }} --non-interactive
      - run: eas update --auto --non-interactive --environment ${{ inputs.environment }}
