name: Mobile Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to build for
        required: true
        type: choice
        options:
          - production
          - preview
  workflow_call:
    inputs:
      environment:
        description: Environment to build for
        required: true
        type: string

defaults:
  run:
    working-directory: 'apps/mobile'

concurrency:
  cancel-in-progress: true
  group: ${{ inputs.environment }}-mobile-build

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm build:android --profile ${{ inputs.environment }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      - id: diawi
        uses: rnkdsh/action-upload-diawi@v1.5.9
        with:
          token: ${{ secrets.DIAWI_TOKEN }}
          file: apps/mobile/build/app.apk
      - run: |
          echo ${{ steps.diawi.outputs.url }}
          echo ${{ steps.diawi.outputs.qrcode }}

  ios:
    name: iOS
    runs-on: macos-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm build:ios --profile ${{ inputs.environment }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      - id: diawi
        uses: rnkdsh/action-upload-diawi@v1.5.9
        with:
          token: ${{ secrets.DIAWI_TOKEN }}
          file: apps/mobile/build/app.ipa
      - run: |
          echo ${{ steps.diawi.outputs.url }}
          echo ${{ steps.diawi.outputs.qrcode }}

  update:
    name: Update
    runs-on: macos-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm add --global eas-cli
      - run: eas update --auto --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
