name: Mobile

on:
  push:
    paths:
      - 'apps/mobile/**'
      - '.github/**'

jobs:
  check:
    name: Check
    uses: ./.github/workflows/mobile-check.yml

  #  production-build:
  #    name: Production Build
  #    if: github.ref == 'refs/heads/main'
  #    needs: [check]
  #    uses: ./.github/workflows/mobile-build.yml
  #    secrets: inherit
  #    with:
  #      environment: production

  staging-build:
    name: Staging Build
    if: github.ref == 'refs/heads/staging'
    needs: [check]
    uses: ./.github/workflows/mobile-build.yml
    secrets: inherit
    with:
      environment: preview
