name: Mobile Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to build for
        required: true
        type: choice
        options:
          - production
          - preview
  workflow_call:
    inputs:
      environment:
        description: Environment to build for
        required: true
        type: string

defaults:
  run:
    working-directory: 'apps/mobile'

concurrency:
  cancel-in-progress: true
  group: ${{ inputs.environment }}-mobile-build

jobs:
  ios:
    name: iOS
    runs-on: macos-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          eas-version: latest
          expo-cache: true
          eas-cache: true
          packager: 'pnpm'
      - run: >
          eas build
          --local
          --non-interactive
          --platform ios
          --profile ${{ inputs.environment }}
          --output app-build.ipa
      - uses: actions/upload-artifact@v4
        with:
          name: imigration.ipa
          path: app-build.ipa

  update:
    name: Update
    runs-on: macos-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          eas-version: latest
          expo-cache: true
          eas-cache: true
          packager: 'pnpm'
      - run: eas update --auto --non-interactive
