name: Mobile Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to build for
        required: true
        type: choice
        options:
          - production
          - preview
  workflow_call:
    inputs:
      environment:
        description: Environment to build for
        required: true
        type: string

defaults:
  run:
    working-directory: 'apps/mobile'

concurrency:
  cancel-in-progress: true
  group: ${{ inputs.environment }}-mobile-build

jobs:
  ios:
    name: iOS
    runs-on: macos-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm add --global eas-cli
      - run: >
          NODE_OPTIONS="--openssl-legacy-provider --max_old_space_size=4096"
          eas build
          --local
          --non-interactive
          --platform ios
          --profile ${{ inputs.environment }}
          --output ${{ github.workspace }}/imigration.ipa
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      - uses: rnkdsh/action-upload-diawi@v1.5.9
        with:
          token: ${{ secrets.DIAWI_TOKEN }}
          file: imigration.ipa

  update:
    name: Update
    runs-on: macos-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm add --global eas-cli
      - run: eas update --auto --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
