name: Platform Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

defaults:
  run:
    working-directory: 'packages/platform'

concurrency:
  cancel-in-progress: true
  group: ${{ inputs.environment }}-platform-deploy

jobs:
  vercel:
    name: Vercel
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm add --global vercel
      - run: vercel pull --yes --environment=${{ inputs.environment }} --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
