name: Platform Check

on:
  workflow_call:

defaults:
  run:
    working-directory: 'packages/supabase'

jobs:
  check:
    name: Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: turbo run lint:check format:check build:check
