name: Platform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: choice
        options:
          - production
          - preview
  workflow_call:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: string

defaults:
  run:
    working-directory: 'apps/platform'

concurrency:
  cancel-in-progress: true
  group: ${{ inputs.environment }}-platform-deploy

jobs:
  vercel:
    name: Vercel
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm exec vercel link --repo --yes --token=${{ secrets.VERCEL_TOKEN }}
      - run: pnpm exec vercel pull --environment ${{ inputs.environment }} --yes --token ${{ secrets.VERCEL_TOKEN }}
      - run: pnpm exec vercel build --target ${{ inputs.environment }} --token ${{ secrets.VERCEL_TOKEN }}
      - run: pnpm exec vercel deploy --target ${{ inputs.environment }} --prebuilt --archive tgz --token ${{ secrets.VERCEL_TOKEN }}
