name: Supabase

on:
  push:
    paths:
      - 'packages/supabase/**'
      - '.github/workflows/supabase*.yml'

  pull_request:
    paths:
      - 'packages/supabase/**'
      - '.github/workflows/supabase*.yml'

jobs:
  check:
    name: Check
    uses: ./.github/workflows/supabase-check.yml

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    needs: check
    uses: ./.github/workflows/supabase-deploy.yml
    secrets: inherit
