name: Supabase Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

defaults:
  run:
    working-directory: 'packages/supabase'

concurrency:
  cancel-in-progress: true
  group: supabase-deploy

jobs:
  migrations:
    name: Migrations
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    concurrency:
      group: supabase-migrations-deploy
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm migrations:push
        env:
          SUPABASE_PROJECT_REF: ${{ vars.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

  config:
    name: Config
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    concurrency:
      group: supabase-config-deploy
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm config:push
        env:
          SUPABASE_PROJECT_REF: ${{ vars.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
