name: Supabase Deploy

on:
  workflow_call:

defaults:
  run:
    working-directory: 'supabase'

jobs:
  db-push:
    name: Push database migrations
    runs-on: ubuntu-latest
    concurrency:
      group: supabase-db-push
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm db:push
        env:
          SUPABASE_PROJECT_REF: ${{ vars.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

  config-push:
    name: Push supabase config
    runs-on: ubuntu-latest
    concurrency:
      group: supabase-config-push
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm config:push
        env:
          SUPABASE_PROJECT_REF: ${{ vars.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
