name: Supabase Check

on:
  workflow_call:

defaults:
  run:
    working-directory: 'packages/supabase'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup
      - run: turbo run lint:check

  db-lint:
    name: Database lint
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup
      - run: pnpm db:start
      - run: pnpm db:lint

  db-diff:
    name: Database diff
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup
      - run: pnpm db:start
      - run: pnpm db:diff:check

  db-dump:
    name: Database dump
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup
      - run: pnpm db:start
      - run: pnpm db:dump:check

  db-test:
    name: Database test
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup
      - run: pnpm db:start
      - run: pnpm db:test

  types:
    name: Types
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup
      - run: pnpm db:start
      - run: pnpm types:check
