name: Supabase Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: environment
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

concurrency:
  cancel-in-progress: true
  group: ${{ inputs.environment }}-supabase-deploy

jobs:
  migrations:
    name: Migrations
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: ./.github/actions/setup
      - run: pnpm migrations:push
        working-directory: 'packages/supabase'
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}

  config:
    name: Config
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: ./.github/actions/setup
      - run: pnpm config:push
        working-directory: 'packages/supabase'
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
