name: Supabase

on:
  push:
    paths:
      - 'packages/supabase/**'
      - '.github/workflows/**'

jobs:
  supabase-check:
    name: Supabase Check
    uses: ./.github/workflows/supabase-check.yml

  check:
    name: Check
    uses: ./.github/workflows/check.yml
    with:
      working-directory: 'packages/supabase'

  deploy-production:
    name: Production Deploy
    if: github.ref == 'refs/heads/main'
    needs: [check, supabase-check]
    uses: ./.github/workflows/supabase-deploy.yml
    secrets: inherit
    with:
      environment: production

  deploy-staging:
    name: Staging Deploy
    if: github.ref == 'refs/heads/staging'
    needs: [check, supabase-check]
    uses: ./.github/workflows/supabase-deploy.yml
    secrets: inherit
    with:
      environment: preview
